### ISSUE TITLE
panic: runtime error on CentOS

### ISSUE THREAD

**Issue by linickx** [ghedo/moodns#1]
Hi,

`moodns` doesn't appear to run on CentOS.

Steps followed:

```
$ sudo yum install golang mercurial
$ git clone git@github.com:ghedo/moodns.git
$ cd moodns
$ make
```

This all completes successfully.

I then run `bin/moodns -l ':5354' -r` and perform a test query...

```
$ dig @localhost -p 5354 nickelmac.local

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.el6_6.1 <<>> @localhost -p 5354 nickelmac.local
; (2 servers found)
;; global options: +cmd
;; connection timed out; no servers could be reached
$ 
```

That host does exist in avahai, as I can ping it by name.... but `moodns` crashes:

```
$ bin/moodns -l ':5354' -r
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x8087738]

goroutine 21 [running]:
runtime.panic(0x818e220, 0x826bcb3)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xe9
mdns.Read(0x184527c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/nick/moodns/src/mdns/net.go:117 +0x208
mdns.Serve(0x184527c0, 0x1840edc0, 0x1843a2c0, 0xc, 0x100)
        /home/nick/moodns/src/mdns/net.go:220 +0x42
created by main.main
        /home/nick/moodns/src/main/moodns/moodns.go:75 +0x528

goroutine 16 [select (no cases)]:
main.main()
        /home/nick/moodns/src/main/moodns/moodns.go:78 +0x547

goroutine 19 [finalizer wait]:
runtime.park(0x8059f10, 0x826ee84, 0x826e269)
        /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x94
runtime.parkunlock(0x826ee84, 0x826e269)
        /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3f
runfinq()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xc5
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
syscall.Syscall(0x3, 0x5, 0x18454000, 0x800, 0x1, 0x8069a6f, 0x8160880)
        /usr/lib/golang/src/pkg/syscall/asm_linux_386.s:19 +0x5
syscall.read(0x5, 0x18454000, 0x800, 0x800, 0x1840e360, 0x0, 0x0)
        /usr/lib/golang/src/pkg/syscall/zsyscall_linux_386.go:838 +0x60
syscall.Read(0x5, 0x18454000, 0x800, 0x800, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/pkg/syscall/syscall_unix.go:136 +0x56
netlink.(*NetlinkListener).ReadMsgs(0x184326b0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/nick/moodns/src/netlink/netlink_linux.go:74 +0xcd
mdns.MonitorNetwork(0x184527c0, 0xb7746308, 0x1840edc0, 0x0, 0x0)
        /home/nick/moodns/src/mdns/net.go:325 +0x7d
created by mdns.NewServer
        /home/nick/moodns/src/mdns/net.go:96 +0xbe
$ 
```

Any idea's what I'm missing?

My computer details are:

```
$ rpm -qa | grep golang
golang-pkg-linux-386-1.3.3-1.el6.noarch
golang-src-1.3.3-1.el6.noarch
golang-pkg-bin-linux-386-1.3.3-1.el6.i686
golang-1.3.3-1.el6.i686
$ rpm -qa | grep mercurial
mercurial-1.4-3.el6.i686
$ cat /etc/centos-release 
CentOS release 6.6 (Final)
$ 
```

Thanks in Advance!

**Comment by ghedo** [comment]
Should be fixed now, thanks for reporting!

**Comment by linickx** [comment]
Thanks! :star2:
